language: cpp
sudo: required
dist: trusty
osx_image: xcode9.3beta
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  include:
    - os: linux
      compiler: gcc
      env: COVERAGE="true"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libreadline-dev
      - libncurses5-dev
      - g++-4.8
      - python-yaml
script:
  - tools/travis/${TRAVIS_OS_NAME}.sh
