language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

# To avoid building everything twice for a PR
branches:
  except: /pr\/.*/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - libreadline-dev
      - libncurses5-dev
      - g++-4.8
      - python-yaml
script:
  - tools/travis_${TRAVIS_OS_NAME}.sh
