language: cpp
sudo: required
dist: trusty
osx_image: xcode10.1
cache: ccache
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - TESTS=unit
  - TESTS=internal
  - TESTS=templight
  - TESTS=clang
  - TESTS=gcc
  - TESTS=wave
  - TESTS=auto
matrix:
  include:
    - os: linux
      compiler: gcc
      env: STATIC_CHECKS="true"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libreadline-dev
      - libncurses5-dev
      - gcc-7
      - g++-7
      - python-yaml
script:
  - tools/travis/${TRAVIS_OS_NAME}.sh
